"""Core constants used across Forge modules.

This module centralizes non-domain-specific constants.
Keeping values here avoids magic literals in business logic.
"""

from __future__ import annotations

from pathlib import Path
from typing import Literal

DEFAULT_DATA_ROOT = Path(".forge")
DATASETS_DIR_NAME = "datasets"
VERSIONS_DIR_NAME = "versions"
CATALOG_FILE_NAME = "catalog.json"
MANIFEST_FILE_NAME = "manifest.json"
RECORDS_FILE_NAME = "records.jsonl"
LANCE_DIR_NAME = "data.lance"
DEFAULT_LANGUAGE_CODE = "unknown"
ENGLISH_LANGUAGE_CODE = "en"
DEFAULT_QUALITY_SCORE = 0.0
DEFAULT_QUALITY_FLOOR = 0.0
DEFAULT_SHUFFLE_BUFFER_SIZE = 1024
DEFAULT_BATCH_SIZE = 16
DEFAULT_MAX_TOKEN_LENGTH = 512
HASH_ALGORITHM = "sha256"
SUPPORTED_TEXT_EXTENSIONS = (".txt", ".md", ".text", ".jsonl")
INGEST_CHECKPOINT_DIR_NAME = "ingest_checkpoint"
CHECKPOINT_STATE_FILE_NAME = "state.json"
CHECKPOINT_SOURCE_RECORDS_FILE_NAME = "source_records.jsonl"
CHECKPOINT_WORK_RECORDS_FILE_NAME = "work_records.jsonl"
CHECKPOINT_UNCHANGED_RECORDS_FILE_NAME = "unchanged_records.jsonl"
CHECKPOINT_DEDUP_RECORDS_FILE_NAME = "dedup_records.jsonl"
CHECKPOINT_ENRICHED_RECORDS_FILE_NAME = "enriched_records.jsonl"
DEFAULT_QUALITY_MODEL = "perplexity"
SUPPORTED_QUALITY_MODELS = ("hybrid", "perplexity")
DEFAULT_EXPORT_SHARD_SIZE = 1000
DEFAULT_TRAIN_EPOCHS = 3
DEFAULT_TRAIN_LEARNING_RATE = 1e-3
DEFAULT_TRAIN_WEIGHT_DECAY = 0.0
DEFAULT_TRAIN_SGD_MOMENTUM = 0.9
DEFAULT_TRAIN_VALIDATION_SPLIT = 0.1
DEFAULT_TRAIN_EMBED_DIM = 128
DEFAULT_TRAIN_HIDDEN_DIM = 256
DEFAULT_TRAIN_NUM_LAYERS = 2
DEFAULT_TRAIN_ATTENTION_HEADS = 8
DEFAULT_TRAIN_MLP_HIDDEN_DIM = 1024
DEFAULT_TRAIN_MLP_LAYERS = 2
DEFAULT_TRAIN_DROPOUT = 0.1
DEFAULT_POSITION_EMBEDDING_TYPE: Literal["learned", "sinusoidal"] = "learned"
SUPPORTED_POSITION_EMBEDDING_TYPES = ("learned", "sinusoidal")
DEFAULT_TRAINED_MODEL_FILE_NAME = "model.pt"
DEFAULT_TRAIN_HISTORY_FILE_NAME = "history.json"
DEFAULT_TRAIN_PLOT_FILE_NAME = "training_curves.png"
DEFAULT_TRAIN_CHECKPOINT_DIR_NAME = "checkpoints"
DEFAULT_TRAIN_BEST_CHECKPOINT_FILE_NAME = "best.pt"
DEFAULT_TRAIN_CHECKPOINT_EVERY_EPOCHS = 1
DEFAULT_TRAIN_MAX_CHECKPOINT_FILES = 5
RUNS_DIR_NAME = "runs"
RUN_INDEX_FILE_NAME = "index.json"
RUN_STATE_FILE_NAME = "lifecycle.json"
LINEAGE_DIR_NAME = "lineage"
LINEAGE_GRAPH_FILE_NAME = "model_lineage.json"
TRAINING_ARTIFACT_CONTRACT_FILE_NAME = "training_artifacts_manifest.json"
DEFAULT_REPRODUCIBILITY_BUNDLE_FILE_NAME = "reproducibility_bundle.json"
DEFAULT_TRAIN_PROGRESS_LOG_INTERVAL_STEPS = 10
DEFAULT_TRAIN_PRECISION_MODE: Literal["auto", "fp32", "fp16", "bf16"] = "auto"
SUPPORTED_TRAIN_PRECISION_MODES = ("auto", "fp32", "fp16", "bf16")
DEFAULT_TRAIN_OPTIMIZER_TYPE: Literal["adam", "adamw", "sgd"] = "adam"
SUPPORTED_TRAIN_OPTIMIZER_TYPES = ("adam", "adamw", "sgd")
DEFAULT_TRAIN_SCHEDULER_TYPE: Literal["none", "step", "cosine"] = "none"
SUPPORTED_TRAIN_SCHEDULER_TYPES = ("none", "step", "cosine")
DEFAULT_TRAIN_SCHEDULER_STEP_SIZE = 1
DEFAULT_TRAIN_SCHEDULER_GAMMA = 0.95
DEFAULT_TRAIN_SCHEDULER_T_MAX_EPOCHS: int | None = None
DEFAULT_TRAIN_SCHEDULER_ETA_MIN = 0.0
DEFAULT_TRAINING_CONFIG_FILE_NAME = "training_config.json"
DEFAULT_TOKENIZER_VOCAB_FILE_NAME = "tokenizer_vocab.json"
DEFAULT_CHAT_MAX_NEW_TOKENS = 80
DEFAULT_CHAT_TEMPERATURE = 0.8
DEFAULT_CHAT_TOP_K = 40
